completed hw 03
MakiievOleksandr/nodejs-hw-restAPI pull request #8
Opened 2023-04-11 19:08 UTC by MakiievOleksandr

check it, please

2023-04-11 20:10 UTC, KhYulian commented on public/server.log
Цей файл видаліть, та додайте в ігнор

2023-04-11 20:11 UTC, KhYulian requested changes
Переконайтесь, що prettier підключений та відпрацьовує, бо у коду проблеми із форматуванням

2023-04-11 20:11 UTC, KhYulian commented on controllers/contactsControllers.js
> +        };
логіку валідації можна винести в окрему middleware, яка спрацьовуватиме перед контроллером

2023-04-12 15:33 UTC, MakiievOleksandr commented on controllers/contactsControllers.js
> +        };
зроблено

2023-04-12 15:34 UTC, MakiievOleksandr commented
перевірте ще раз, будь ласка!

2023-04-12 18:51 UTC, KhYulian approved these changes
Чудова робота!

2023-04-12 18:51 UTC, merged